name: PHPUnit Test
on:
  - push
jobs:
  test:
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        php-version:
          - '8.1'
    name: php ${{ matrix.php-version }} on ${{ matrix.operating-system }}
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: bcmath, ctype, dom, fileinfo, json, libxml, mbstring, openssl, pdo, tokenizer, xml, zip
          coverage: none
      - name: Prepare the environment
        run: cp .env.example .env
      - name: Configure NPM
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install composer dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        run: composer dumpautoload -o --no-interaction
      - name: Install NPM Dependencies
        run: npm install
      - name: Generate Application Key
        run: php artisan key:generate --env=testing
      - name: Clear Application Cache
        run: php artisan optimize:clear
      - name: Run PHPUnit Tests
        run: php artisan test --parallel
        env:
          DB_CONNECTION: mysql
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          DB_USERNAME: root
          DB_DATABASE: test
          DB_PASSWORD: null
